name: development

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: provision
        run: make provision

      - name: check
        run: make check

      - name: build
        run: make build

      - name: test
        run: make test
