name: main

on:
  push:
    branches:
      - 'main'

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: provision
        run: make provision

      - name: check
        run: make check

      - name: build
        run: make build

      - name: test
        run: make test

      - name: setup-git
        run: ./bin/annie set git

      - name: release
        run: |
          CURRENT_VERSION=$(./bin/annie get version)
          NEXT_VERSION=$(./bin/annie predict version)
          echo current version: $CURRENT_VERSION
          echo next version: $NEXT_VERSION
          ./bin/annie release version
          git push origin $NEXT_VERSION
