name: main

on:
  push:
    branches:
      - 'main'

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup-git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: provision
        run: make provision

      - name: check
        run: make check

      - name: build
        run: make build

      - name: test
        run: make test

      - name: release
        run: |
          CURRENT_VERSION=$(./bin/bone version get)
          ./bin/bone version up
          NEXT_VERSION=$(./bin/bone version get)
          git push origin $NEXT_VERSION
